### ISSUE TITLE
PA Review: Authentication

### ISSUE THREAD

**Issue by Alspirid** [Alspirid/Lounge-search#1]
- [x] Backend: DB, model, controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x] Presentational Components
 - [x] Styling
 - [x] Smooth, bug-free navigation
 - [x] Adequate and appropriate seeds

**Comment by evhumphrey** [comment]
Looks good!

A few things: 

- [x] Hover effects on nav bar could be improved 
- [x] Add a hover effect to the modal buttons 
- [x] Have "Log In" modal have consistent language (instead of "sign in" in the title, have "Log In")
