### ISSUE TITLE
PA Review: Location search

### ISSUE THREAD

**Issue by Alspirid** [Alspirid/Lounge-search#3]
- [ ] Backend: controller, views
 - [ ] Redux Loop: ajax, actions, reducer
 - [ ] Presentational Components
 - [ ] Styling
 - [ ] Smooth, bug-free navigation
 - [ ] Adequate and appropriate seeds

**Comment by evhumphrey** [comment]
Also looks good!

A few things: 
- [x] I would add a hover effect to the location items
- [x] When you click on a location, clicking on the users should link to their user profile page 
- [x] When you search, I wouldn't clear the search input (so a user can see what their search text was)

**Comment by Alspirid** [comment]
Thank you for the review. All 3 items have been fixed.
Please take a look.

**Comment by evhumphrey** [comment]
👍
