### ISSUE TITLE
PA Review: Dashboard/User Profile

### ISSUE THREAD

**Issue by Alspirid** [Alspirid/Lounge-search#4]
- [x] Backend: controller, views
 - [x] Redux Loop: ajax, actions, reducer
 - [x] Presentational Components
 - [x] Styling
 - [x] Smooth, bug-free navigation
 - [x] Adequate and appropriate seeds

**Comment by anastassia-b** [comment]
When we met, we fixed the routes and the props matched to your dashboard container. Your next step is to: 
- [x] Make the demo user as seed data and repush to heroku (and seed).

**Comment by evhumphrey** [comment]
Nice, looks good!

- [x] I would make sure to style your name to show that "Dashboard" is the current page you are on. Look into `NavLink`. You'll want to do this with Locations as well

**Comment by Alspirid** [comment]
Not really clear how name should be styled.. We need to discuss proposed change.

**Comment by evhumphrey** [comment]
Whoops that was a typo, was supposed to say "Nav"
![screen shot 2018-02-08 at 10 49 16 am](https://user-images.githubusercontent.com/6361824/35991976-c450ec04-0cbd-11e8-80d3-da8623880565.png)

**Comment by evhumphrey** [comment]
Quick thing I noticed: 
When clicking on a user from the locations, the page shows dotted outlines. I would remove these. 
![screen shot 2018-02-08 at 10 44 21 am](https://user-images.githubusercontent.com/6361824/35991773-11fdbcc6-0cbd-11e8-8749-3690c292e4f4.png)

Also, on your dashboard, you have some locations. If you decide to keep this, I would have these be clickable links to the locations. 
![screen shot 2018-02-08 at 10 47 05 am](https://user-images.githubusercontent.com/6361824/35991989-cfe046dc-0cbd-11e8-81f4-00ee1d45452b.png)

**Comment by Alspirid** [comment]
Ready for review
